# Generated by Django 4.2.29 on 2026-04-06 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_instructor_pending',
            field=models.BooleanField(default=False, verbose_name='Đang chờ duyệt giảng viên'),
        ),
    ]
