# Generated by Django 4.2.29 on 2026-04-05 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonprogress',
            name='is_saved',
            field=models.BooleanField(default=False),
        ),
    ]
