# Generated by Django 4.2.29 on 2026-04-06 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_lessonprogress_is_saved'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Tên tài liệu/Sách')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='document_covers/', verbose_name='Ảnh bìa')),
                ('file', models.FileField(upload_to='documents/', verbose_name='File tài liệu (PDF, Word...)')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả ngắn')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Tài liệu & Sách',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
