# Generated by Django 4.2.29 on 2026-04-06 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_document_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Số thứ tự (Lộ trình)'),
        ),
    ]
